name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm ci
        continue-on-error: true
      - name: Print npm log if failure
        if: ${{ failure() }}
        run: cat /home/runner/.npm/_logs/*-debug.log
      - run: npm test
