name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x' # Automatically use the latest version of Node.js 14
      
      - name: Install dependencies
        run: npm ci
        continue-on-error: true # Continue even if this step fails

      - name: Print npm log if failure
        if: failure() # Simplified conditional check
        run: cat /home/runner/.npm/_logs/*-debug.log # Make sure this path is correct
      
      - name: Run tests
        run: npm test # Explicitly named this step for clarity
