name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x' # Use the latest version of Node.js 14.x

      - name: Install dependencies
        run: npm ci # Installs node modules as per the lock file

      - name: Run tests
        run: npm test # Executes tests

